Makefile: add .SILENT to all Makefiles and remove @...s

diff --git a/Makefile-128 b/Makefile-128
--- a/Makefile-128
+++ b/Makefile-128
@@ -8,7 +8,9 @@
 ## 
 ################################################################################
 
-MYMAKE			= $(MAKE) -f Makefile-128 -j8
+.SILENT:
+
+MYMAKE			= $(MAKE) -s -f Makefile-128 -j8
 ZPRAGMA_INC             = zpragma-128.inc
 
 # All taps
@@ -22,17 +24,17 @@ CFLAGS			+= -pragma-define:REGISTER_SP=$(ISR_VECTOR_ADDRESS_128)
 .PHONY: datasets codesets taps
 
 build:
-	@$(MYMAKE) banked_definitions
-	@$(MYMAKE) datasets
-	@$(MYMAKE) codesets
-	@$(MYMAKE) banked_code BANKED_CFLAGS=-D_BANKED_CODE_BUILD
-	@$(MYMAKE) banks
-	@$(MYMAKE) main
-	@$(MYMAKE) bank_switcher
-	@$(MYMAKE) loader
-	@$(MYMAKE) taps
-	@$(MYMAKE) final
-	@$(MYMAKE) lowmemcheck
+	$(MYMAKE) banked_definitions
+	$(MYMAKE) datasets
+	$(MYMAKE) codesets
+	$(MYMAKE) banked_code BANKED_CFLAGS=-D_BANKED_CODE_BUILD
+	$(MYMAKE) banks
+	$(MYMAKE) main
+	$(MYMAKE) bank_switcher
+	$(MYMAKE) loader
+	$(MYMAKE) taps
+	$(MYMAKE) final
+	$(MYMAKE) lowmemcheck
 
 ## Check that certain symbols are linked in low memory.  It is assumed that
 ## all symbols mentioned as "extern" in .h files will be accessed from
@@ -56,7 +58,7 @@ ALL_LOWMEM_SYMBOLS	= $(ENGINE_LOWMEM_SYMBOLS) $(GAME_LOWMEM_SYMBOLS) $(CODE_LOWM
 
 # target for doing the real check
 lowmemcheck:
-	@./tools/lowmemsym.pl -m main.map $(ALL_LOWMEM_SYMBOLS)
+	./tools/lowmemsym.pl -m main.map $(ALL_LOWMEM_SYMBOLS)
 
 ##
 ## Dataset compilation to standalone binaries org'ed at 0x5C00
@@ -65,20 +67,20 @@ lowmemcheck:
 datasets: $(ZX0_DATASETS)
 
 dataset_%.bin:
-	@echo "Compiling DATASET $@ ..."
-	@# the '.../*.{asm,c}' at the end of the next line is critical: asm files MUST be included before C ones!
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) --no-crt -o $@ $(GENERATED_DIR_DATASETS)/$(shell basename $@ .bin).src/*.{asm,c}
-	@cp $@ $@.save
-	@echo "-- $$( basename $@ ) uncompressed size: $$( stat -c%s $@ ) bytes"
-	@if [ $$( stat -c%s $@ ) -gt $(DATASET_MAXSIZE) ]; then \
+	echo "Compiling DATASET $@ ..."
+	# the '.../*.{asm,c}' at the end of the next line is critical: asm files MUST be included before C ones!
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) --no-crt -o $@ $(GENERATED_DIR_DATASETS)/$(shell basename $@ .bin).src/*.{asm,c}
+	cp $@ $@.save
+	echo "-- $$( basename $@ ) uncompressed size: $$( stat -c%s $@ ) bytes"
+	if [ $$( stat -c%s $@ ) -gt $(DATASET_MAXSIZE) ]; then \
 		echo "** ERROR: $$( basename $@ ) size ($$( stat -c%s $@ ) bytes) is greater than $(DATASET_MAXSIZE) bytes"; \
 		exit 1; \
 	fi
 
 dataset_%.zx0: dataset_%.bin
-	@echo "Compressing DATASET $< ..."
-	@$(ZX0) $< $@ >/dev/null 2>&1
-	@echo "-- $$( basename $@ ) compressed size: $$( stat -c%s $@ ) bytes"
+	echo "Compressing DATASET $< ..."
+	$(ZX0) $< $@ >/dev/null 2>&1
+	echo "-- $$( basename $@ ) compressed size: $$( stat -c%s $@ ) bytes"
 
 ##
 ## Codeset compilation to standalone binaries org'ed at 0xC000
@@ -88,11 +90,11 @@ codesets: $(BIN_CODESETS)
 
 #codeset_%.bin: codeset_%.src/*.c codeset_%.src/*.asm
 codeset_%.bin:
-	@echo "Compiling CODESET $@ ..."
-	@# the '.../*.{asm,c}' at the end of the next line is critical: asm files MUST be included before C ones!
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) -I$(GAME_SRC_DIR) --no-crt -o $@ $(GENERATED_DIR_CODESETS)/$(shell basename $@ .bin).src/*.{asm,c}
-	@mv $(GENERATED_DIR_CODESETS)/$(shell basename $@ .bin)_code_compiler.bin $@
-	@if [ $$( stat -c%s $@ ) -gt $(CODESET_MAXSIZE) ]; then echo "** ERROR: $$( basename $@ ) size is greater than $(CODESET_MAXSIZE) bytes"; exit 1; fi
+	echo "Compiling CODESET $@ ..."
+	# the '.../*.{asm,c}' at the end of the next line is critical: asm files MUST be included before C ones!
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) -I$(GAME_SRC_DIR) --no-crt -o $@ $(GENERATED_DIR_CODESETS)/$(shell basename $@ .bin).src/*.{asm,c}
+	mv $(GENERATED_DIR_CODESETS)/$(shell basename $@ .bin)_code_compiler.bin $@
+	if [ $$( stat -c%s $@ ) -gt $(CODESET_MAXSIZE) ]; then echo "** ERROR: $$( basename $@ ) size is greater than $(CODESET_MAXSIZE) bytes"; exit 1; fi
 
 ##
 ## Banked code compilation to standalone binary at 0xC000
@@ -100,37 +102,37 @@ codeset_%.bin:
 ##
 
 banked_definitions:
-	@./tools/check_banked_code_definitions.pl
+	./tools/check_banked_code_definitions.pl
 
 banked_code: $(BIN_BANKED_CODE)
 
 $(BIN_BANKED_CODE): $(BANKED_CODE_OBJS_COMMON) $(BANKED_CODE_OBJS_128)
-	@echo "Building $@..."
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) -m $(BANKED_CFLAGS) --no-crt -o $@ $(BANKED_CODE_OBJS_128) $(BANKED_CODE_OBJS_COMMON)
-	@mv $(BANKED_CODE_DIR)/$(shell basename $@ .bin)_code_compiler.bin $@
-	@if [ $$( stat -c%s $@ ) -gt $(BANK_MAXSIZE) ]; then echo "** ERROR: $$( basename $@ ) size is greater than $(BANK_MAXSIZE) bytes"; exit 1; fi
+	echo "Building $@..."
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) -m $(BANKED_CFLAGS) --no-crt -o $@ $(BANKED_CODE_OBJS_128) $(BANKED_CODE_OBJS_COMMON)
+	mv $(BANKED_CODE_DIR)/$(shell basename $@ .bin)_code_compiler.bin $@
+	if [ $$( stat -c%s $@ ) -gt $(BANK_MAXSIZE) ]; then echo "** ERROR: $$( basename $@ ) size is greater than $(BANK_MAXSIZE) bytes"; exit 1; fi
 
 ##
 ## Dataset/Codeset Banks
 ##
 
 banks:
-	@echo "Building Bank binaries and Dataset/Codeset maps..."
-	@./tools/banktool.pl -i $(GENERATED_DIR_DATASETS) -c $(GENERATED_DIR_CODESETS) -o $(GENERATED_DIR) -l $(GENERATED_DIR_LOWMEM)
+	echo "Building Bank binaries and Dataset/Codeset maps..."
+	./tools/banktool.pl -i $(GENERATED_DIR_DATASETS) -c $(GENERATED_DIR_CODESETS) -o $(GENERATED_DIR) -l $(GENERATED_DIR_LOWMEM)
 
 bank_switcher: $(BSWITCH_BIN)
 
 $(BSWITCH_BIN):
-	@echo "Assembling bank switch routine..."
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) --list --no-crt $(BSWITCH_SRC) -o $(BSWITCH_BIN)
+	echo "Assembling bank switch routine..."
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) --list --no-crt $(BSWITCH_SRC) -o $(BSWITCH_BIN)
 
 ##
 ## Custom BASIC loader
 ##
 
 loader:
-	@echo "Creating custom BASIC loader..."
-	@./tools/loadertool.pl -i $(GENERATED_DIR) -o $(GENERATED_DIR) $(LOADING_SCREEN_FLAG)
+	echo "Creating custom BASIC loader..."
+	./tools/loadertool.pl -i $(GENERATED_DIR) -o $(GENERATED_DIR) $(LOADING_SCREEN_FLAG)
 
 ##
 ## Taps
@@ -140,26 +142,26 @@ taps: $(TAPS)
 
 # we set org at 0xC000 for the banks
 bank_%.tap: bank_%.bin
-	@echo "Creating TAP $@..."
-	@z88dk-appmake +zx --noloader --org 0xC000 -b $<
+	echo "Creating TAP $@..."
+	z88dk-appmake +zx --noloader --org 0xC000 -b $<
 
 # we set org at base code address for 128 mode, 0x5F00 for 48 mode
 $(MAIN_TAP): $(MAIN_BIN)
-	@echo "Creating TAP $@..."
-	@z88dk-appmake +zx --noloader --org $(BASE_CODE_ADDRESS_128) -b $<
+	echo "Creating TAP $@..."
+	z88dk-appmake +zx --noloader --org $(BASE_CODE_ADDRESS_128) -b $<
 
 # we set org at 0x8000 for bank switcher
 $(BSWITCH_TAP): $(BSWITCH_BIN)
-	@echo "Creating TAP $@..."
-	@z88dk-appmake +zx --noloader --org 0x8000 -b $<
+	echo "Creating TAP $@..."
+	z88dk-appmake +zx --noloader --org 0x8000 -b $<
 
 ##
 ## Main
 ##
 
 $(MAIN_BIN): $(OBJS)
-	@echo "Bulding $(MAIN_BIN)...."
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(INCLUDE) $(LIBDIR) $(LIBS) $(OBJS) -startup=31 -o $(MAIN_BIN)
+	echo "Bulding $(MAIN_BIN)...."
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(INCLUDE) $(LIBDIR) $(LIBS) $(OBJS) -startup=31 -o $(MAIN_BIN)
 
 ##
 ## Run options
diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -8,6 +8,8 @@
 ## 
 ################################################################################
 
+.SILENT:
+
 # directory configurations
 ENGINE_DIR			= engine
 BUILD_DIR			= build
@@ -115,18 +117,18 @@ endif
 
 # generic rules
 %.o: %.c
-	@echo Compiling $*.c ...
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(BANKED_CFLAGS) -c $*.c
+	echo Compiling $*.c ...
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(BANKED_CFLAGS) -c $*.c
 
 %.o: %.asm
-	@echo Assembling $*.asm ...
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(BANKED_CFLAGS) -c $*.asm
+	echo Assembling $*.asm ...
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(BANKED_CFLAGS) -c $*.asm
 
 # rule for inspecting generated asm code - run 'make myfile.c.asm' to
 # get the .c.asm assembler generated from C file, with C code as comments
 %.c.asm: %.c
-	@echo Generating ASM for $*.c ...
-	@$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(CFLAGS_TO_ASM) -c $*.c
+	echo Generating ASM for $*.c ...
+	$(ZCC) $(ZCC_TARGET) $(CFLAGS) $(CFLAGS_LIST) $(CFLAGS_TO_ASM) -c $*.c
 
 # build targets
 .PHONY: data all build clean clean-config data_depend build-data help final taps main tests
@@ -138,10 +140,10 @@ final: $(FINAL_TAP)
 ##
 
 $(GENERATED_DIR)/game_data_home.c: $(GENERATED_DIR)/game_data.dep
-	@$(MYMAKE) -s data
+	$(MYMAKE) data
 
 $(GENERATED_DIR_DATASETS)/game_data_banked.c: $(GENERATED_DIR)/game_data.dep
-	@$(MYMAKE) -s data
+	$(MYMAKE) data
 
 $(GENERATED_DIR)/game_data.dep: data_depend
 
@@ -154,36 +156,36 @@ GDATA_FILES =	$(wildcard $(GAME_DATA_DIR)/game_config/*.gdata) \
 GDATA_PATCHES =	$(wildcard $(GAME_DATA_DIR)/patches/map/*.gdata) $(wildcard $(GAME_DATA_DIR)/patches/flow/*.gdata)
 
 data:
-	@$(DATAGEN) -t $(ZX_TARGET) -c -d $(GENERATED_DIR) $(GDATA_FILES) $(GDATA_PATCHES)
-	@./tools/generate_banked_function_defs.pl
+	$(DATAGEN) -t $(ZX_TARGET) -c -d $(GENERATED_DIR) $(GDATA_FILES) $(GDATA_PATCHES)
+	./tools/generate_banked_function_defs.pl
 
 data_depend:
-	@if [ ! -f $(GENERATED_DIR)/game_data.dep ]; then ls -1 $(GDATA_FILES) $(GDATA_PATCHES) | xargs -l stat -c '%n%Y' | sha256sum > $(GENERATED_DIR)/game_data.dep; fi
-	@ls -1 $(GDATA_FILES) $(GDATA_PATCHES) | xargs -l stat -c '%n%Y' | sha256sum > /tmp/game_data.dep
-	@if ( ! cmp -s $(GENERATED_DIR)/game_data.dep /tmp/game_data.dep ) then rm $(GENERATED_DIR)/game_data.dep; mv /tmp/game_data.dep $(GENERATED_DIR)/game_data.dep; fi
+	if [ ! -f $(GENERATED_DIR)/game_data.dep ]; then ls -1 $(GDATA_FILES) $(GDATA_PATCHES) | xargs -l stat -c '%n%Y' | sha256sum > $(GENERATED_DIR)/game_data.dep; fi
+	ls -1 $(GDATA_FILES) $(GDATA_PATCHES) | xargs -l stat -c '%n%Y' | sha256sum > /tmp/game_data.dep
+	if ( ! cmp -s $(GENERATED_DIR)/game_data.dep /tmp/game_data.dep ) then rm $(GENERATED_DIR)/game_data.dep; mv /tmp/game_data.dep $(GENERATED_DIR)/game_data.dep; fi
 
 ## Taps
 
 taps: $(TAPS)
 
 %.tap: %.bas
-	@echo "Creating TAP $@..."
-	@bas2tap -sLOADER -a10 -q $<
+	echo "Creating TAP $@..."
+	bas2tap -sLOADER -a10 -q $<
 
 $(FINAL_TAP): $(TAPS)
-	@echo "Building final TAP $(FINAL_TAP)..."
-	@cat $(TAPS) > $(FINAL_TAP)
-	@echo "Build completed SUCCESSFULLY"
+	echo "Building final TAP $(FINAL_TAP)..."
+	cat $(TAPS) > $(FINAL_TAP)
+	echo "Build completed SUCCESSFULLY"
 
 screen.tap:
-	@echo "Adding loading SCREEN$$..."
-	@-rm -f /tmp/screen.scr 2>/dev/null
-#	@echo "PNG:" '"$(LOADING_SCREEN_PNG)"'
-#	@echo "SCR:" '"$(LOADING_SCREEN_SCR)"'
-	@if [ ! -z "$(LOADING_SCREEN_SCR)" ] && [ ! -z "$(LOADING_SCREEN_PNG)" ]; then echo "** Error: LOADING_SCREEN: PNG and SCR cannot de used at the same time"; exit 1; fi
-	@if [ ! -z "$(LOADING_SCREEN_SCR)" ]; then cp "$(BUILD_DIR)/$(LOADING_SCREEN_SCR)" /tmp/screen.scr; else ./tools/png2scr.pl "$(BUILD_DIR)/$(LOADING_SCREEN_PNG)" /tmp/screen.scr; fi
-	@if [ "$$(wc -c /tmp/screen.scr | awk '{print $$1}')" -ne 6912 ]; then echo "** Error: LOADING_SCREEN must be exactly 6912 bytes long"; exit 1 ; fi
-	@z88dk-appmake +zx --noloader --org 16384 -b /tmp/screen.scr -o screen.tap
+	echo "Adding loading SCREEN$$..."
+	-rm -f /tmp/screen.scr 2>/dev/null
+#	echo "PNG:" '"$(LOADING_SCREEN_PNG)"'
+#	echo "SCR:" '"$(LOADING_SCREEN_SCR)"'
+	if [ ! -z "$(LOADING_SCREEN_SCR)" ] && [ ! -z "$(LOADING_SCREEN_PNG)" ]; then echo "** Error: LOADING_SCREEN: PNG and SCR cannot de used at the same time"; exit 1; fi
+	if [ ! -z "$(LOADING_SCREEN_SCR)" ]; then cp "$(BUILD_DIR)/$(LOADING_SCREEN_SCR)" /tmp/screen.scr; else ./tools/png2scr.pl "$(BUILD_DIR)/$(LOADING_SCREEN_PNG)" /tmp/screen.scr; fi
+	if [ "$$(wc -c /tmp/screen.scr | awk '{print $$1}')" -ne 6912 ]; then echo "** Error: LOADING_SCREEN must be exactly 6912 bytes long"; exit 1 ; fi
+	z88dk-appmake +zx --noloader --org 16384 -b /tmp/screen.scr -o screen.tap
 
 ## Main game
 
@@ -194,21 +196,21 @@ main: $(MAIN_BIN)
 ##
 
 show:
-	@echo "Game Configuration : $(shell grep -E '^\s*NAME\s+' build/game_data/game_config/Game.gdata | head -1 | awk '{print $$2}' )"
-	@echo "Build Configuration: $(ZX_TARGET)K"
+	echo "Game Configuration : $(shell grep -E '^\s*NAME\s+' build/game_data/game_config/Game.gdata | head -1 | awk '{print $$2}' )"
+	echo "Build Configuration: $(ZX_TARGET)K"
 
 ##
 ## Run options
 ##
 
 run:
-	@fuse $(FUSE_RUN_OPTS) $(FINAL_TAP) --debugger-command ''
+	fuse $(FUSE_RUN_OPTS) $(FINAL_TAP) --debugger-command ''
 
 debug:
-	@fuse $(FUSE_RUN_OPTS) $(FINAL_TAP) --debugger-command "$$(cat debug_script.cfg | ./tools/r1sym.pl -m main.map )"
+	fuse $(FUSE_RUN_OPTS) $(FINAL_TAP) --debugger-command "$$(cat debug_script.cfg | ./tools/r1sym.pl -m main.map )"
 
 runz:
-	@../zesarux/src/zesarux $(FINAL_TAP)
+	../zesarux/src/zesarux $(FINAL_TAP)
 
 ##
 ## Tests
@@ -249,44 +251,44 @@ LIB_GAME_DATA_DIRS	= $(TEST_GAMES_DIR)/minimal/game_data $(TEST_GAMES_DIR)/minim
 
 # create a minimal game using the library
 new-game:
-	@if [ -z "$(target)" ]; then echo "Usage: make new-game target=<game-directory>"; exit 1; fi
-	@if [ -d "$(target)" ]; then echo "Existing game directory $(target) found, won't overwrite!"; exit 2; fi
-	@echo "Creating game directory $(target)..."
-	@mkdir -p "$(target)/"
-	@echo -n "Syncing library and game template files... "
-	@rsync -ap $(LIB_GAME_DATA_DIRS) "$(target)"
-	@rsync -ap Makefile.game "$(target)/Makefile"
-	@echo "Done!"
+	if [ -z "$(target)" ]; then echo "Usage: make new-game target=<game-directory>"; exit 1; fi
+	if [ -d "$(target)" ]; then echo "Existing game directory $(target) found, won't overwrite!"; exit 2; fi
+	echo "Creating game directory $(target)..."
+	mkdir -p "$(target)/"
+	echo -n "Syncing library and game template files... "
+	rsync -ap $(LIB_GAME_DATA_DIRS) "$(target)"
+	rsync -ap Makefile.game "$(target)/Makefile"
+	echo "Done!"
 
 # tools
 mem_obj:
-	@echo ""; echo "MEMORY USAGE REPORT BY OBJECT FILE:"
-	@./tools/r1size.sh
+	echo ""; echo "MEMORY USAGE REPORT BY OBJECT FILE:"
+	./tools/r1size.sh
 
 mem_main:
-	@echo ""; echo "MEMORY USAGE REPORT BY BINARY SECTION (MAIN MEMORY):"
-	@./tools/memmap.pl -m -p main main.map
+	echo ""; echo "MEMORY USAGE REPORT BY BINARY SECTION (MAIN MEMORY):"
+	./tools/memmap.pl -m -p main main.map
 
 mem_bank:
-	@echo ""; echo "MEMORY USAGE REPORT BY BINARY SECTION (BANKED MEMORY):"
-	@./tools/memmap.pl -m -p bank $(BANKED_CODE_DIR)/banked_code.map
+	echo ""; echo "MEMORY USAGE REPORT BY BINARY SECTION (BANKED MEMORY):"
+	./tools/memmap.pl -m -p bank $(BANKED_CODE_DIR)/banked_code.map
 
 mem-old: mem_main mem_bank
 
 mem:
-	@./tools/mem-summary.sh
+	./tools/mem-summary.sh
 
 linecount: clean
-	@echo -n "Lines of Code (C):         "
-	@find . -type f |grep -v -E '^./.git'|grep -v tests/|xargs -l file|grep -E 'C source'|cut -f1 -d:|xargs -l cat|wc -l
-	@echo -n "Lines of Code (Perl):      "
-	@find . -type f |grep -v -E '^./.git'|grep -v tests/|xargs -l file|grep -E 'Perl'|cut -f1 -d:|xargs -l cat|wc -l
-	@echo -n "Lines of Code (Assembler): "
-	@find . -type f -iname "*.asm"|grep -v -E '^./.git'|grep -v tests/|xargs -l cat|wc -l
-	@echo -n "Lines of Docs:             "
-	@find doc/ -type f|xargs cat|wc -l
-	@echo -n "Lines of Test Games:       "
-	@find $(TEST_GAMES_DIR)/ -type f|xargs -l cat|wc -l
+	echo -n "Lines of Code (C):         "
+	find . -type f |grep -v -E '^./.git'|grep -v tests/|xargs -l file|grep -E 'C source'|cut -f1 -d:|xargs -l cat|wc -l
+	echo -n "Lines of Code (Perl):      "
+	find . -type f |grep -v -E '^./.git'|grep -v tests/|xargs -l file|grep -E 'Perl'|cut -f1 -d:|xargs -l cat|wc -l
+	echo -n "Lines of Code (Assembler): "
+	find . -type f -iname "*.asm"|grep -v -E '^./.git'|grep -v tests/|xargs -l cat|wc -l
+	echo -n "Lines of Docs:             "
+	find doc/ -type f|xargs cat|wc -l
+	echo -n "Lines of Test Games:       "
+	find $(TEST_GAMES_DIR)/ -type f|xargs -l cat|wc -l
 
 LIS2ADDR = ../zxtools/bin/lis2addr.pl
 
diff --git a/Makefile.game b/Makefile.game
--- a/Makefile.game
+++ b/Makefile.game
@@ -18,33 +18,33 @@ RAGE1REPO = https://github.com/jorgegv/rage1.git
 
 # game targets
 info:
-	@echo "Game Directory: $(GAMEDIR)"
-	@echo "RAGE1 Directory: $(RAGE1DIR)"
-	@echo "RAGE1 Tag: $(RAGE1_TAG)"
+	echo "Game Directory: $(GAMEDIR)"
+	echo "RAGE1 Directory: $(RAGE1DIR)"
+	echo "RAGE1 Tag: $(RAGE1_TAG)"
 
 rage1-clone:
 	if [ ! -d "$(RAGE1DIR)" ]; then git clone "$(RAGE1REPO)" "$(RAGE1DIR)" ]; fi
 	cd "$(RAGE1DIR)" && git checkout master && git pull --all
 
 rage1-checkout: rage1-clone
-	@bash -c "( cd '$(RAGE1DIR)' && git co $(RAGE1_TAG) >/dev/null 2>&1 ) || echo 'Git: error checking out $(RAGE1_TAG)'"
+	bash -c "( cd '$(RAGE1DIR)' && git co $(RAGE1_TAG) >/dev/null 2>&1 ) || echo 'Git: error checking out $(RAGE1_TAG)'"
 
 build: info rage1-checkout
-	@bash -c "cd $(RAGE1DIR) && make -s build target_game=$(GAMEDIR)" | tee build.log
+	bash -c "cd $(RAGE1DIR) && make build target_game=$(GAMEDIR)" | tee build.log
 	cp "$(RAGE1DIR)/game.tap" .
 
 build-debug: info rage1-checkout
-	@bash -c "cd $(RAGE1DIR) && make -s build-debug target_game=$(GAMEDIR)" | tee build.log
+	bash -c "cd $(RAGE1DIR) && make build-debug target_game=$(GAMEDIR)" | tee build.log
 	cp "$(RAGE1DIR)/game.tap" .
 
 run:
-	@bash -c "cd $(RAGE1DIR) && make -s run"
+	bash -c "cd $(RAGE1DIR) && make run"
 
 mem:
-	@bash -c "cd $(RAGE1DIR) && make -s mem"
+	bash -c "cd $(RAGE1DIR) && make mem"
 
 mem-128:
-	@bash -c "cd $(RAGE1DIR) && make -s mem-128"
+	bash -c "cd $(RAGE1DIR) && make mem-128"
 
 # include additional rules specified in the game, if any
 include Makefile.custom
